### ISSUE TITLE
2018年11月29日よりGoogle翻訳の仕様変更

### ISSUE THREAD

**Issue by yammyi** [komiyamma/hidemaru-net#1]
2018年11月29日より
Google翻訳の仕様変更によりHmGoogleTranslator.js が動作しなくなっております。

**Comment by komiyamma** [comment]
報告ありがとうございます。動作しませんね。タグなどの変更を確認してみます～。

**Comment by yammyi** [comment]
HmLangTranslator アップデートありがとうございます。
感謝して使わせていただいております。

更新してみましたが、アウトプットに以下がでて動作しない様子でした。
hmV8も最新です。
--------------------------------
翻訳対象が存在していません。
(対象テキストを選択してない等)
------------------------------
他に使われているユーザー様いらっしゃいませんか？

**Comment by komiyamma** [comment]
ご報告ありがとうございます。
遅れておりまして、すみません。

HmLangTranslatorですが、**GoogleAppScript でHubを作る**形に変更していますが、
この肝心のHubの作り方を記載していないので、
動作させられないと思います。
１～２週間以内に、HmLangTranslator を含めて、
・Github
・秀丸マクロ.net, 
・秀丸本家サイトのマクロ登録コーナー
を更新したいと思います。

GoogleAppScript  経由であれば、googleのアカウントさえもっていれば、
「各人が自分で作ったAPIのURL」というものを実行できるようになっていますので、
**仕様の変更といったものが発生しにくい** ので良いかと思っています。
この各人が自分で作ったAPIの入り口で、「翻訳」をしてしまえば、
GoogleのWeb翻訳の仕様に左右されず、翻訳することが可能になっています。

①Web翻訳(無料だが、Webページなので、そもそも仕様が安定しない)
②Google Translate API(こっちだとクレカの登録が必要)
③Google App Script(クレカの登録などは不要。API経由)

１～２週間以内に公開、更新予定（いずれも、GoogleAppScriptのHubに乗っかる形)
・翻訳に機能を絞っているHmPython3版（現在非公開⇒公開）
・同 C# 版（現在非公開⇒公開）
・ECMAScript版のHmLangTranslator⇒更新

以上を予定しています、よろしくお願いします。

**Comment by komiyamma** [comment]
一旦、Google 翻訳系は、
https://hide.maruo.co.jp/lib/macro/google_app_script_lang_trans.html

で３種アップしました。

HmLangTranslator も 数日内にこれと同じ Google Apps Script を使ったものへと切り替えて
アップ予定となります。

**Comment by komiyamma** [comment]
HmLangTranslator も同様の方法(Google Apps Script)での設定を行うように変更しました。
http://xn--pckzexbx21r8q9b.net/?page=nobu_tool_hm_lang_translator
