### ISSUE TITLE
hm.NET - 名前が同じで引数が異なるメソッド呼び出し不可問題

### ISSUE THREAD

**Issue by Hidemaruo** [komiyamma/hidemaru-net#2]
https://www.maruo.co.jp/hidesoft/2/x38448_.html
にて話が上がってるのですが、hm.NETでの話として、名前が同じで引数が異なるメソッドの呼び出しが出来ない問題があります。

解決策というか、ソースコードの修正例も、上記会議室にありますので、是非バージョンアップお願いしたいです。

**Comment by komiyamma** [comment]
Hidemaruoさん、（ひでまるおさん!?） お返事が大変おくれました。 
（会社のうち20年続いた数百人のグループが10月になくなると決定したので対応に追われてまして...orz)

会議室を拝見しますと、お返事が遅れたことで、話が膨らんでいる!?

ソースコードの修正例の提示ありがとうございます。こちらでも確認してverをアップしてみます。

**Comment by komiyamma** [comment]
こちら実装しをえているため、クローズします。
