### ISSUE TITLE
dsds

### ISSUE THREAD

**Issue by intercoursewithyourmom** [komiyamma/hidemaru-net#9]
wenomechainsama

**Comment by doomed-phobos** [comment]
yandere :v

~~porque hidemaru-net :'v?~~

**Comment by intercoursewithyourmom** [comment]
1. No se como se usa GitHub, no entiendo  n a d a
2.  Man, pq te fuiste de Instagram? Se te extraña :'(

**Comment by doomed-phobos** [comment]
hdp esto no es una red social

**Comment by intercoursewithyourmom** [comment]
De eso me di cuenta ya hace tiempo, perdón por la molestia, no era la intención

**Comment by intercoursewithyourmom** [comment]
Oye, por cierto empecé a ver Stein:Gate (solamente los primeros dos capítulos porque mis audífonos se descompusieron aaa)

**Comment by intercoursewithyourmom** [comment]
@intercoursewithyourmom
